# Generated by Django 2.1.3 on 2019-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField(verbose_name='Ценности')),
                ('goals', models.TextField(verbose_name='Цели')),
                ('hobbies', models.TextField(verbose_name='Хобби')),
                ('about_me', models.TextField(verbose_name='Обо мне')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_skills', models.TextField(verbose_name='Скиллы')),
                ('html_css', models.IntegerField(verbose_name='HTML/CSS')),
                ('js', models.IntegerField(verbose_name='JS')),
                ('python_django', models.IntegerField(verbose_name='Python(Django)')),
                ('sql', models.IntegerField(verbose_name='SQL')),
            ],
            options={
                'verbose_name': 'Скиллы',
                'verbose_name_plural': 'Скиллы',
            },
        ),
    ]
