# Generated by Django 2.1.3 on 2019-07-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_education', models.TextField(verbose_name='Об образовании')),
                ('sertificate', models.CharField(max_length=255, verbose_name='Диплом')),
                ('degree', models.CharField(max_length=255, verbose_name='Место учебы')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('about_degree', models.TextField(verbose_name='О учебе')),
            ],
            options={
                'verbose_name': 'Образвание',
                'verbose_name_plural': 'Образвание',
            },
        ),
        migrations.CreateModel(
            name='MyExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_experience', models.TextField(verbose_name='О работе')),
                ('worked_as', models.CharField(max_length=255, verbose_name='Работал')),
                ('place', models.CharField(max_length=255, verbose_name='Место работы')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('about_job', models.TextField(verbose_name='О работе')),
            ],
            options={
                'verbose_name': 'Опыт Работы',
                'verbose_name_plural': 'Опыт Работы',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_portfolio', models.TextField(verbose_name='О портфолио')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
        ),
    ]
