# Generated by Django 2.1.3 on 2019-07-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_myeducation_myexperience_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
    ]
