# Generated by Django 2.1.3 on 2019-07-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_myeducation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='myexperience',
            name='year',
            field=models.IntegerField(blank=True, default=0, verbose_name='Лет Работы'),
        ),
    ]
