# Generated by Django 2.1.3 on 2019-07-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='values',
            field=models.TextField(blank=True, verbose_name='Ценности'),
        ),
        migrations.AlterField(
            model_name='myeducation',
            name='about_education',
            field=models.TextField(blank=True, verbose_name='Об образовании'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='about_experience',
            field=models.TextField(blank=True, verbose_name='О работе'),
        ),
        migrations.AlterField(
            model_name='myskills',
            name='about_skills',
            field=models.TextField(blank=True, verbose_name='Скиллы'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='about_portfolio',
            field=models.TextField(blank=True, verbose_name='О портфолио'),
        ),
    ]
